title: Welcome to My Page # name of the site
author: wikankun # name of site's author
email: wikankun@gmail.com # email of site's author
url: https://wikankun.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  <p>
  <br>
  <b>Wikan Kuncara Jati</b>
  <br>
  I'm a programmer with 3+ years of experiences<br>
  And the founder of Price History ID<br><br>
  Interest: gaming, programming, backend, data engineering<br>
  Dislikes: frontend, CS student who says "CS student don't have to be able to code"<br>
  Motto: from random import *<br><br>
  ↓ will update soon
  </p>

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
